### ISSUE TITLE
Unable to connect to controller

### ISSUE THREAD

**Issue by davidvlasic** [hjdhjd/homebridge-unifi-access#9]
### Homebridge UniFi Access Version

v1.2.1

### Homebridge Platform and OS

Synology Docker Ubuntu Focal Fossa (20.04.4 LTS)

### Homebridge Version

Homebridge v1.7.0

### Node Version

v20.11.1

### UniFi OS Version

v3.2.12

### UniFi Access Controller Version

v1.23.12

### Describe the problem

I have the homebridge unifi protect plugin running fine with the same config details, but the homebridge unifi access plugin, either is unable to connect to the controller  "192.168.1.1: API error: Unable to connect to the Access controller. This is usually temporary and will occur during Access controller reboots and firmware updates."

The user is a local user (same as protect) and has full access to all elements (network, protect, access and os).  If I change the credentials to an deliberately incorrect user I get "192.168.1.1: API error: Insufficient privileges for this user. Please check the roles assigned to this user and ensure it has sufficient privileges."  which seems to suggest a connection is attempted and the controller is reached, but rejected.

### Homebridge HBUA JSON configuration

```json
{
    "controllers": [
        {
            "address": "192.168.1.1",
            "password": "password",
            "username": "api"
        }
    ],
    "name": "UniFi Access",
    "_bridge": {
        "username": "0E:42:92:7A:8A:3B",
        "port": 35325
    },
    "platform": "UniFi Access"
}
```

### Relevant log output

```shell
[3/26/2024, 1:21:39 PM] [UniFi Access] Restarting child bridge...
[3/26/2024, 1:21:39 PM] [UniFi Access] Restarting Process...
[3/26/2024, 1:21:40 PM] [UniFi Access] Launched child bridge with PID 27007
[3/26/2024, 1:21:40 PM] Registering platform 'homebridge-unifi-access.UniFi Access'
[3/26/2024, 1:21:40 PM] [UniFi Access] Loaded homebridge-unifi-access v1.2.1 child bridge successfully
[3/26/2024, 1:21:40 PM] Loaded 0 cached accessories from cachedAccessories.0E42927A8A3B.
[3/26/2024, 1:21:41 PM] Homebridge v1.7.0 (HAP v0.11.1) (UniFi Access) is running on port 35325.
(node:27007) [DEP0123] DeprecationWarning: Setting the TLS ServerName to an IP address is not permitted by RFC 6066. This will be ignored in a future version.
(Use `node --trace-deprecation ...` to show where the warning was created)
[3/26/2024, 1:21:42 PM] [UniFi Access] 192.168.1.1: API error: Insufficient privileges for this user. Please check the roles assigned to this user and ensure it has sufficient privileges.
[3/26/2024, 1:21:52 PM] [UniFi Access] 192.168.1.1: API error: Insufficient privileges for this user. Please check the roles assigned to this user and ensure it has sufficient privileges.
[3/26/2024, 1:22:04 PM] [UniFi Access] 192.168.1.1: API error: Insufficient privileges for this user. Please check the roles assigned to this user and ensure it has sufficient privileges.
[3/26/2024, 1:22:14 PM] [UniFi Access] 192.168.1.1: API error: Insufficient privileges for this user. Please check the roles assigned to this user and ensure it has sufficient privileges.
[3/26/2024, 1:22:24 PM] [UniFi Access] 192.168.1.1: API error: Unable to connect to the Access controller. This is usually temporary and will occur during Access controller reboots and firmware updates.
[3/26/2024, 1:22:34 PM] [UniFi Access] 192.168.1.1: API error: Unable to connect to the Access controller. This is usually temporary and will occur during Access controller reboots and firmware updates.
[3/26/2024, 1:22:45 PM] [UniFi Access] 192.168.1.1: API error: Unable to connect to the Access controller. This is usually temporary and will occur during Access controller reboots and firmware updates.
[3/26/2024, 1:22:55 PM] [UniFi Access] 192.168.1.1: API error: Unable to connect to the Access controller. This is usually temporary and will occur during Access controller reboots and firmware updates.
[3/26/2024, 1:23:05 PM] [UniFi Access] 192.168.1.1: API error: Unable to connect to the Access controller. This is usually temporary and will occur during Access controller reboots and firmware updates.
[3/26/2024, 1:23:15 PM] [UniFi Access] 192.168.1.1: API error: Unable to connect to the Access controller. This is usually temporary and will occur during Access controller reboots and firmware updates.
[3/26/2024, 1:23:22 PM] [UniFi Access] Restarting child bridge...
[3/26/2024, 1:23:22 PM] Got SIGTERM, shutting down child bridge process...
[3/26/2024, 1:23:25 PM] [UniFi Access] 192.168.1.1: API error: Unable to connect to the Access controller. This is usually temporary and will occur during Access controller reboots and firmware updates.
[3/26/2024, 1:23:27 PM] [UniFi Access] Child bridge process ended
[3/26/2024, 1:23:27 PM] [UniFi Access] Process Ended. Code: 143, Signal: null
[3/26/2024, 1:23:34 PM] [UniFi Access] Restarting Process...
[3/26/2024, 1:23:35 PM] [UniFi Access] Launched child bridge with PID 28509
[3/26/2024, 1:23:35 PM] Registering platform 'homebridge-unifi-access.UniFi Access'
[3/26/2024, 1:23:35 PM] [UniFi Access] Loaded homebridge-unifi-access v1.2.1 child bridge successfully
[3/26/2024, 1:23:35 PM] Loaded 0 cached accessories from cachedAccessories.0E42927A8A3B.
[3/26/2024, 1:23:35 PM] Homebridge v1.7.0 (HAP v0.11.1) (UniFi Access) is running on port 35325.
(node:28509) [DEP0123] DeprecationWarning: Setting the TLS ServerName to an IP address is not permitted by RFC 6066. This will be ignored in a future version.
(Use `node --trace-deprecation ...` to show where the warning was created)
TypeError: Cannot read properties of undefined (reading 'device_groups')
    at file:///homebridge/node_modules/homebridge-unifi-access/node_modules/unifi-access/src/access-api.ts:292:45
    at Array.map (<anonymous>)
    at AccessApi.bootstrapController (file:///homebridge/node_modules/homebridge-unifi-access/node_modules/unifi-access/src/access-api.ts:292:34)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at AccessController.retry (file:///homebridge/node_modules/homebridge-unifi-access/src/access-controller.ts:550:10)
    at AccessController.bootstrapController (file:///homebridge/node_modules/homebridge-unifi-access/src/access-controller.ts:70:5)
    at AccessController.login (file:///homebridge/node_modules/homebridge-unifi-access/src/access-controller.ts:106:5)
[3/26/2024, 1:23:37 PM] [UniFi Access] Child bridge process ended
[3/26/2024, 1:23:37 PM] [UniFi Access] Process Ended. Code: 1, Signal: null
[3/26/2024, 1:23:44 PM] [UniFi Access] Restarting Process...
[3/26/2024, 1:23:44 PM] [UniFi Access] Launched child bridge with PID 28647
[3/26/2024, 1:23:45 PM] Registering platform 'homebridge-unifi-access.UniFi Access'
[3/26/2024, 1:23:45 PM] [UniFi Access] Loaded homebridge-unifi-access v1.2.1 child bridge successfully
[3/26/2024, 1:23:45 PM] Loaded 0 cached accessories from cachedAccessories.0E42927A8A3B.
[3/26/2024, 1:23:45 PM] Homebridge v1.7.0 (HAP v0.11.1) (UniFi Access) is running on port 35325.
(node:28647) [DEP0123] DeprecationWarning: Setting the TLS ServerName to an IP address is not permitted by RFC 6066. This will be ignored in a future version.
(Use `node --trace-deprecation ...` to show where the warning was created)
TypeError: Cannot read properties of undefined (reading 'device_groups')
    at file:///homebridge/node_modules/homebridge-unifi-access/node_modules/unifi-access/src/access-api.ts:292:45
    at Array.map (<anonymous>)
    at AccessApi.bootstrapController (file:///homebridge/node_modules/homebridge-unifi-access/node_modules/unifi-access/src/access-api.ts:292:34)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at AccessController.retry (file:///homebridge/node_modules/homebridge-unifi-access/src/access-controller.ts:550:10)
    at AccessController.bootstrapController (file:///homebridge/node_modules/homebridge-unifi-access/src/access-controller.ts:70:5)
    at AccessController.login (file:///homebridge/node_modules/homebridge-unifi-access/src/access-controller.ts:106:5)
[3/26/2024, 1:23:46 PM] [UniFi Access] Child bridge process ended
[3/26/2024, 1:23:46 PM] [UniFi Access] Process Ended. Code: 1, Signal: null
[3/26/2024, 1:23:53 PM] [UniFi Access] Restarting Process...
[3/26/2024, 1:23:54 PM] [UniFi Access] Launched child bridge with PID 28774
[3/26/2024, 1:23:54 PM] Registering platform 'homebridge-unifi-access.UniFi Access'
[3/26/2024, 1:23:54 PM] [UniFi Access] Loaded homebridge-unifi-access v1.2.1 child bridge successfully
[3/26/2024, 1:23:54 PM] Loaded 0 cached accessories from cachedAccessories.0E42927A8A3B.
[3/26/2024, 1:23:55 PM] Homebridge v1.7.0 (HAP v0.11.1) (UniFi Access) is running on port 35325.
(node:28774) [DEP0123] DeprecationWarning: Setting the TLS ServerName to an IP address is not permitted by RFC 6066. This will be ignored in a future version.
(Use `node --trace-deprecation ...` to show where the warning was created)
TypeError: Cannot read properties of undefined (reading 'device_groups')
    at file:///homebridge/node_modules/homebridge-unifi-access/node_modules/unifi-access/src/access-api.ts:292:45
    at Array.map (<anonymous>)
    at AccessApi.bootstrapController (file:///homebridge/node_modules/homebridge-unifi-access/node_modules/unifi-access/src/access-api.ts:292:34)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at AccessController.retry (file:///homebridge/node_modules/homebridge-unifi-access/src/access-controller.ts:550:10)
    at AccessController.bootstrapController (file:///homebridge/node_modules/homebridge-unifi-access/src/access-controller.ts:70:5)
    at AccessController.login (file:///homebridge/node_modules/homebridge-unifi-access/src/access-controller.ts:106:5)
[3/26/2024, 1:23:56 PM] [UniFi Access] Child bridge process ended
[3/26/2024, 1:23:56 PM] [UniFi Access] Process Ended. Code: 1, Signal: null
[3/26/2024, 1:24:03 PM] [UniFi Access] Restarting Process...
[3/26/2024, 1:24:04 PM] [UniFi Access] Launched child bridge with PID 28912
[3/26/2024, 1:24:04 PM] [UniFi Access] Loaded homebridge-unifi-access v1.2.1 child bridge successfully
[3/26/2024, 1:24:06 PM] [UniFi Access] Child bridge process ended
[3/26/2024, 1:24:06 PM] [UniFi Access] Process Ended. Code: 1, Signal: null
[3/26/2024, 1:24:13 PM] [UniFi Access] Restarting Process...
[3/26/2024, 1:24:14 PM] [UniFi Access] Launched child bridge with PID 29050
[3/26/2024, 1:24:14 PM] [UniFi Access] Loaded homebridge-unifi-access v1.2.1 child bridge successfully
[3/26/2024, 1:24:15 PM] [UniFi Access] Child bridge process ended
[3/26/2024, 1:24:15 PM] [UniFi Access] Process Ended. Code: 1, Signal: null
[3/26/2024, 1:24:22 PM] [UniFi Access] Restarting Process...
[3/26/2024, 1:24:23 PM] [UniFi Access] Launched child bridge with PID 29177
[3/26/2024, 1:24:24 PM] [UniFi Access] Loaded homebridge-unifi-access v1.2.1 child bridge successfully
[3/26/2024, 1:24:24 PM] [UniFi Access] 192.168.1.1: API error: Unable to connect to the Access controller. This is usually temporary and will occur during Access controller reboots and firmware updates.
[3/26/2024, 1:24:34 PM] [UniFi Access] 192.168.1.1: API error: Unable to connect to the Access controller. This is usually temporary and will occur during Access controller reboots and firmware updates.
[3/26/2024, 1:24:45 PM] [UniFi Access] Child bridge process ended
[3/26/2024, 1:24:45 PM] [UniFi Access] Process Ended. Code: 1, Signal: null
```

### Acknowledgment that you are only running UniFi OS and UniFi Access releases from the Ubiquiti Official release channel

- [X] I acknowledge that I am not running any early access / beta firmwares or operating systems from either Ubiquiti or Apple.

**Comment by hjdhjd** [comment]
Thanks for raising the issue - can you give the latest update a try and see if it helps?

**Comment by davidvlasic** [comment]
Worked immediately!  Thank you so much for your help - this has been the missing link for so long.

**Comment by hjdhjd** [comment]
Glad to hear it! Thanks for the report.
